all:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/mykey.pem

web:
  hosts:
    web1.example.com:
      ansible_host: 192.168.1.101
    web2.example.com:
      ansible_host: 192.168.1.102
  vars:
    http_port: 80
    max_clients: 200

db:
  hosts:
    db1.example.com:
      ansible_host: 192.168.1.201
  vars:
    db_name: mydatabase
    db_user: dbuser
    db_password: secret
